apiVersion: apps/v1
kind: Deployment
metadata:
  name: cobol-app
  labels:
    app: cobol-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cobol-app
  template:
    metadata:
      labels:
        app: cobol-app
    spec:
      containers:
      - name: cobol-container
        image: seu-registry/cobol-app:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      nodeSelector:
        kubernetes.io/arch: arm64
